name: LogisticsApi
main: com.logisticscraft.logisticsapi.LogisticsApi
version: ${project.version}
authors: [PROgrm_JARvis, tr7zw, RoboTricker, sgdc3]
softdepend: [PlaceholderAPI]
commands:
  logisticsapi:
    description: 'Base command of Logistics-API running at the moment'
    aliases: [logisticapi, logistics, logistic, lapi, la, l]