name: LogisticsExample
main: com.logisticscraft.logisticsexample.LogisticsExamplePlugin
version: ${project.version}
api-version: 1.13
authors: [PROgrm_JARvis, tr7zw, RoboTricker, sgdc3]
softdepend: [LogisticsApi]
